config/routes.rb
Revily::Web::Application.routes.draw do
  root to: 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#old_create'
  delete 'sign_out' => 'sessions#destroy'

  resources :events, only: [ :index, :show ]

  resources :services do
    member do
      put 'enable'
      put 'disable'
    end
    resources :incidents do
      member do
        put 'acknowledge'
        put 'resolve'
        put 'trigger'
      end
    end
  end

  resources :incidents, except: [ :new, :create ] do
    member do
      put 'acknowledge'
      put 'resolve'
      put 'trigger'
    end
  end

  resources :policies do
    resources :policy_rules do
      collection do
        post :sort
      end
    end
  end

  resources :schedules do
    resources :schedule_layers, path: :layers, as: :layers
    resources :schedule_layers
    member do
      get 'policy_rules'
      get 'users'
      get 'on_call'
    end
  end


  resources :users do
    resources :contacts
  end
  resources :contacts, except: [ :new, :create ]

  resources :hooks

  # TODO: remove this
  get '_inspect' => 'sessions#_inspect'
end

app/models/incident.rb
class Incident
  include Revily::Model

  attributes :message, :description, :details, :key

  belongs_to :service
  belongs_to :current_user, class_name: "User"
  belongs_to :current_policy_rule, class_name: "PolicyRule"

  validates :message, presence: true

  resource_path "incidents/:id"
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  respond_to :html

  before_action :authenticate!
  before_action :service
  before_action :incidents

  def index
    @incidents = incidents.page(params[:page]).where(unresolved: true)

    respond_with @incidents
  end

  def show
    @incident = incidents.find(params[:id])

    respond_with @incident
  end

  def new
    @incident = incidents.build

    respond_with @incident
  end

  def create
    @incident = incidents.build(incident_params)
    @incident.save

    respond_with @incident
  end

  private

  def service
    @service = Service.find(params[:service_id]) if params[:service_id]
  end

  def incidents
    @incidents = (@service) ? @service.incidents : Incident.all
  end
end

app/views/incidents/_form.html.erb
<%= form_for(@incident, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @incident.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h4>

      <ul>
      <% @incident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :message, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :message, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :details, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :state, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :key, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :key, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :current_user, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :current_user, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :current_policy_rule, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :current_policy_rule, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :escalation_loop_count, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :escalation_loop_count, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :service, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/incidents/edit.html.erb
<div class="page-header">
  <%= link_to incidents_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @incident, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing incident</h1>
</div>

<%= render 'form' %>

app/views/incidents/index.html.erb
<div class="page-header">
  <h1>Listing incidents</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Message</th>
            <th>Description</th>
            <th>Details</th>
            <th>State</th>
            <th>Key</th>
            <th>Current user</th>
            <th>Current policy rule</th>
            <th># Times escalated</th>
            <th>Service</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @incidents) do |incident| %>
            <td><%= incident.message %></td>
            <td><%= incident.description %></td>
            <td><%= incident.details %></td>
            <td><%= incident.state %></td>
            <td><%= incident.key %></td>
            <td><%= incident.current_user.name %></td>
            <td><%= incident.current_policy_rule.position %></td>
            <td><%= incident.escalation_loop_count %></td>
            <td><%= incident.service.name %></td>
            <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
        <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/incidents/new.html.erb
<div class="page-header">
  <%= link_to incidents_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New incident</h1>
</div>

<%= render 'form' %>

app/views/incidents/show.html.erb
<div class="page-header">
  <%= link_to incidents_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Incident <%= @incident.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Message:</dt>
  <dd><%= @incident.message %></dd>

  <dt>Description:</dt>
  <dd><%= @incident.description %></dd>

  <dt>Details:</dt>
  <dd><%= @incident.details %></dd>

  <dt>State:</dt>
  <dd><%= @incident.state %></dd>

  <dt>Key:</dt>
  <dd><%= @incident.key %></dd>

  <dt>Current user:</dt>
  <dd><%= @incident.current_user.name %></dd>

  <dt>Current policy rule:</dt>
  <dd><%= @incident.current_policy_rule.position %></dd>

  <dt>Escalation loop count:</dt>
  <dd><%= @incident.escalation_loop_count %></dd>

  <dt>Service:</dt>
  <dd><%= @incident.service.name %></dd>

</dl>