config/routes.rb
Revily::Web::Application.routes.draw do
  root to: 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#old_create'
  delete 'sign_out' => 'sessions#destroy'

  resources :events, only: [ :index, :show ]

  resources :services do
    member do
      put 'enable'
      put 'disable'
    end
    resources :incidents do
      member do
        put 'acknowledge'
        put 'resolve'
        put 'trigger'
      end
    end
  end

  resources :incidents, except: [ :new, :create ] do
    member do
      put 'acknowledge'
      put 'resolve'
      put 'trigger'
    end
  end

  resources :policies do
    resources :policy_rules do
      collection do
        post :sort
      end
    end
  end

  resources :schedules do
    resources :schedule_layers, path: :layers, as: :layers
    resources :schedule_layers
    member do
      get 'policy_rules'
      get 'users'
      get 'on_call'
    end
  end


  resources :users do
    resources :contacts
  end
  resources :contacts, except: [ :new, :create ]

  resources :hooks

  # TODO: remove this
  get '_inspect' => 'sessions#_inspect'
end

app/models/hook.rb
class Hook
  include Revily::Model

  attributes :name, :config, :events
end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
  respond_to :html

  before_action :authenticate!
  before_action :hooks

  # GET /hooks
  def index
    @hooks = hooks.page(params[:page])

    respond_with @hooks
  end

  # GET /hooks/1
  def show
    @hook = hooks.find(params[:id])

    respond_with @hook
  end

  # GET /hooks/new
  def new
    @hook = hooks.build

    respond_with @hook
  end

  # POST /hooks
  def create
    @hook = hooks.build(hook_params)

    if @hook.save
      respond_with @hook, notice: 'Hook was successfully created.'
    else
      render action: 'new'
    end
  end
  
  # GET /hooks/1/edit
  def edit
    @hook = hooks.find(params[:id])

    respond_with @hook
  end

  # PATCH/PUT /hooks/1
  def update
    @hook = hooks.find(params[:id])

    if @hook.update(hook_params)
      respond_with @hook, notice: 'Hook was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /hooks/1
  def destroy
    @hook = hooks.find(params[:id])

    @hook.destroy
    respond_with @hook, notice: 'Hook was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def hooks
      @hooks = Hook.all
    end

    # Only allow a trusted parameter "white list" through.
    def hook_params
      params.permit(:name, :config, :events)
    end
end

app/views/hooks/_form.html.erb
<%= form_for(@hook) do |f| %>
  <% if @hook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hook.errors.count, "error") %> prohibited this hook from being saved:</h2>

      <ul>
      <% @hook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hooks/edit.html.erb
<h1>Editing hook</h1>

<%= render 'form' %>

<%= link_to 'Show', @hook %> |
<%= link_to 'Back', hooks_path %>

app/views/hooks/index.html.erb
<% @hooks.each do |hook| %>
  <%== ap hook %>
<% end %>

app/views/hooks/new.html.erb
<h1>New hook</h1>

<%= render 'form' %>

<%= link_to 'Back', hooks_path %>

app/views/hooks/show.html.erb
<%== ap @hook %>