config/routes.rb
Revily::Web::Application.routes.draw do
  root to: 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#old_create'
  delete 'sign_out' => 'sessions#destroy'

  resources :events, only: [ :index, :show ]

  resources :services do
    member do
      put 'enable'
      put 'disable'
    end
    resources :incidents do
      member do
        put 'acknowledge'
        put 'resolve'
        put 'trigger'
      end
    end
  end

  resources :incidents, except: [ :new, :create ] do
    member do
      put 'acknowledge'
      put 'resolve'
      put 'trigger'
    end
  end

  resources :policies do
    resources :policy_rules do
      collection do
        post :sort
      end
    end
  end

  resources :schedules do
    resources :schedule_layers, path: :layers, as: :layers
    resources :schedule_layers
    member do
      get 'policy_rules'
      get 'users'
      get 'on_call'
    end
  end


  resources :users do
    resources :contacts
  end
  resources :contacts, except: [ :new, :create ]

  resources :hooks

  # TODO: remove this
  get '_inspect' => 'sessions#_inspect'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  before_action :set_access_token
  
  protected

  def authenticate!
    redirect_to sign_in_url, alert: "You must be logged in first" if current_user.nil?
  end

  def set_access_token
    RequestStore.store[:access_token] ||= session[:access_token]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?
    !!current_user
  end

  # def access_token
    # @access_token ||= RequestStore.store[:access_token]
  # end

  # def access_token=(token)
    # RequestStore.store[:access_token] ||=
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_block
    output = ''
    flash.each do |type, message|
      type = :success if type == :notice
      type = :error   if type == :alert
      type = ""       if type == :info
      output += flash_container(type, message)
    end

    raw(output)
  end

  def flash_container(type, message)
    raw(content_tag(:div, class: "alert-box #{type.to_s}") do
      content_tag(:a, raw("&times;"), class: 'close') + message
    end)
  end

  def modal_dialog(options = {}, escape = true, &block)
    default_options = {class: "bootstrap-modal modal"}
    content_tag :div, nil, options.merge(default_options), escape, &block
  end

  def modal_header(options = {}, escape = true, &block)
    default_options = {class: 'modal-header'}
    content_tag :div, nil, options.merge(default_options), escape do
      raw("<button class=\"close\" data-dismiss=\"modal\">&times;</button>" + capture(&block))
    end
  end

  def modal_body(options = {}, escape = true, &block)
    default_options = {class: 'modal-body'}
    content_tag :div, nil, options.merge(default_options), escape, &block
  end

  def modal_footer(options = {}, escape = true, &block)
    default_options = {class: 'modal-footer'}
    content_tag :div, nil, options.merge(default_options), escape, &block
  end

  def modal_toggle(content_or_options = nil, options = {}, &block)
    if block_given?
      options = content_or_options if content_or_options.is_a?(Hash)
      default_options = {class: 'btn', "data-toggle" => "modal", "href" => options[:dialog]}.merge(options)

      content_tag :a, nil, default_options, true, &block
    else
      default_options = {class: 'btn', "data-toggle" => "modal", "href" => options[:dialog]}.merge(options)
      content_tag :a, content_or_options, default_options, true
    end
  end

  def modal_cancel_button content, options = {}
    default_options = {class: "btn bootstrap-modal-cancel-button"}

    content_tag_string "a", content, default_options.merge(options)
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", "")})
  end

  def icon_links
    content_tag :link, nil, href: "images/apple-touch-icon-144x144.png", rel: "apple-touch-icon-precomposed", sizes: "144x144"
    content_tag :link, nil, href: "images/apple-touch-icon-72x72.png", rel: "apple-touch-icon-precomposed", sizes: "72x72"
    content_tag :link, nil, href: "images/apple-touch-icon.png", rel: "apple-touch-icon-precomposed"
    content_tag :link, nil, href: "favicon.ico", rel: "shortcut icon"
  end

end

app/views/application/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= msg %>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer id="footer">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <p>Copyright &copy; 2013, Applied Awesome LLC.</p>
    </nav>
  </div>
</div>

app/views/application/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Revily", "#", :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/settings">Settings</a></li>
        <li><a href="/sign_out">Sign out</a></li>
      </ul>
    </div>
  </div>
</header>

app/views/application/_sidebar.html.erb
<ul class="nav nav-stacked">
  <li><%= link_to "Incidents", incidents_path %></li>
  <li><%= link_to "Services", services_path %></li>
  <li><%= link_to "Policies", policies_path %></li>
  <li><%= link_to "Schedules", schedules_path %></li>
  <li><%= link_to "Users", users_path %></li>
  <li><%= link_to "Events", events_path %></li>
</ul>